# develop.yaml
name: Development Pipeline
on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Run Tests
      uses: echo "running the test"
    - name: Build Dev Docker Image
      uses: echo "docker image build"
